### ISSUE TITLE
Help Bar is initially closed

### ISSUE THREAD

**Issue by hazolsky** [LiveTyping/android-colors#17]
When you open the app for the first time, the Help Bar is not visible.
Env: prod
Browser: Chrome 60

This happens when `isVisibleHeaderHelpBlock` is not set (which is an initial state for the local storage):
https://github.com/LiveTyping/android-colors/blob/5ef9b59a388a4164a099a5ec58717b40ff92eb83/src/actions/header.js#L21-L27

**Comment by n-filatov** [comment]
@hazolsky fixed https://github.com/LiveTyping/android-colors/pull/24 close issue if fix is ok
