### ISSUE TITLE
Color selection is changing palette table column width

### ISSUE THREAD

**Issue by hazolsky** [LiveTyping/android-colors#22]
When i click on a color hash code to enter a new value, an input field appears and breaks the layout.
See [this screencast](https://spacestore.s3.amazonaws.com/s/9emy8.mp4).

Expected behaviour: an input field matches the column width.

**Comment by n-filatov** [comment]
@hazolsky close if https://github.com/LiveTyping/android-colors/pull/25 fixed it

**Comment by hazolsky** [comment]
As of now it is still happening. Though, the column width is not changing that much.
I'd like to bring in some clarification here: the input field that appears when user clicks on the row should match the exact width and height of the color label and should not change column's layout.

https://spacestore.s3.amazonaws.com/s/qtcgn.mp4
